export const ActionTypes = {
  CHANGE_TICKER: `DATA/CHANGE_TICKER`,
  LOAD_ORDERBOOK: `DATA/LOAD_ORDERBOOK`,
  CHANGE_LOAD_ORDERBOOK: `DATA/CHANGE_LOAD_ORDERBOOK`,
  ADD_ORDERBOOK: `DATA/ADD_ORDERBOOK`,
};
